name: Update Projects Readme's

on:
  schedule:
    - cron: "0 0 1 * *" # This will run the action at 00:00 on the first day of every month
  workflow_dispatch: # This allows you to manually trigger the action

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Run script
        run: |
          chmod +x ./fetch_projects.sh
          ./fetch_projects.sh

      - name: Commit and push changes
        run: |
          git config --global user.email "me@divyb.xyz"
          git config --global user.name "TGDivy"
          git add -A
          git commit -m "Chore: Fetch and Update Projects Readme's"
          git push
