name: Update Projects Readme's

on:
  schedule:
    - cron: "0 0 1 * *" # This will run the action at 00:00 on the first day of every month
  workflow_dispatch: # This allows you to manually trigger the action

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: git config --global user.email "divy.work@outlook.com"
      - run: git config --global user.name "tgdivy"

      - name: Fetch Projects Readme's and Media Files
        run: |
          chmod +x ./fetch_projects.sh
          ./fetch_projects.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Chore: Fetch and Update Projects Readme's"
          git push
